language: ruby

branches:
  only:
    - master

sudo: false

rvm:
  - 2.3.1

install: bundle install --jobs=3 --retry=3 --without kitchen_vagrant kitchen_rackspace kitchen_ec2 development
cache:
  directories:
  - vendor/bundle

script:
  - bundle exec rake style
  - bundle exec rake spec

notifications:
  disable: true
